### ISSUE TITLE
Email Alert

### ISSUE THREAD

**Issue by mgarcen** [altimetrik-onboarding-uy/mgarcen#5]
-As a registered user, after submitting a timesheet, if registered Gross Pay is $2000 or higher, or Total Hours are 40 or more, I should receive an email with the timesheet data, to have a record of my submission.

**Comment by stefaniaoverman** [comment]
Maybe: As a registered user, after submitting a timesheet, if registered Gross Pay is $2000 or higher, or Total Hours are 40 or more, I should receive an email with the timesheet data, **in order to** have a record (platform independent) of my submission.

**Comment by mgarcen** [comment]
Done.
