### ISSUE TITLE
Timesheet List

### ISSUE THREAD

**Issue by mgarcen** [altimetrik-onboarding-uy/mgarcen#6]
-As a registered user I should have the Timesheet list simplified(customized) in the Timesheet Tab, making a friendlier viewing of said list.

**Comment by stefaniaoverman** [comment]
I would say: -As a registered user I should have the Timesheet list simplified(customized) in the Timesheet Tab, **In order to have** a friendlier view of said list.

**Comment by mgarcen** [comment]
Done.
